services:
  app:
    container_name: app
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        SPRING_DATASOURCE_URL: ${DB_URL}
        SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    env_file:
      - app.env
    networks:
      - app_network
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8-oracle
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'Asia/Seoul'
    env_file:
      - db.env
    ports:
      - "3306:3306"
    networks:
      - app_network

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - app


networks:
  app_network:
    driver: bridge


