services:
  app:
    container_name: app
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - app.env
    networks:
      - app_network
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: mysql:8-oracle
    env_file:
      - db.env
    ports:
      - "3306:3306"
    networks:
      - app_network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - app


networks:
  app_network:
    driver: bridge


