name: githubaction

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}


    services:
      mysql:
        image: mysql:8-oracle
        env:
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{  secrets.DATABASE_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew clean build

      - name: make zip
        run: zip -qq -r app.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp app.zip s3://demogithubactionbucket/appbucket/app.zip

      - name: Aws Code Deploy
        run: aws deploy create-deployment --application-name githubaction
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name democicdgroup
          --s3-location bucket=demogithubactionbucket,bundleType=zip,key=app.zip
